{{- if and .Values.cluster.create (not .Values.gateway.pg.existingSecret) }}
{{- $name := include "documentdb-gw.pgSecretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
{{- $pw := "" }}
{{- if and $existing $existing.data (index $existing.data "password") }}
{{-   $pw = index $existing.data "password" | b64dec }}
{{- else }}{{- $pw = randAlphaNum 24 }}{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "documentdb-gw.labels" . | nindent 4 }}
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.gateway.pg.user }}
  password: {{ $pw | quote }}
{{- end }}
