name: lint-title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  pr-lint:
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: morrisoncole/pr-lint-action@51f3cfabaf5d46f94e54524214e45685f0401b2a # v1.7.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title-regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([\w\+\.\/\-]+\))?(!)?: [a-z].+'
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: false
          on-failed-regex-request-changes: false
